- name: Look up the VM called test_vm1 in the inventory
  register: vm_lookup_result
  vmware.vmware_rest.vcenter_vm_info:
    filter_names: "{{ vm_names }}"

- name: Collect information about a specific VM
  register: get_vm_info_result
  vmware.vmware_rest.vcenter_vm_info:
    vm: '{{ vm_lookup_result.value[0].vm }}'

- name: Get guest identity information
  vmware.vmware_rest.vcenter_vm_guest_identity_info:
    vm: '{{ get_vm_info_result.id }}'
  register: vm_info_result

- name: Log vm_info_result
  tags: always
  when: vm_info_result is defined
  ansible.builtin.debug:
    var: vm_info_result
    verbosity: 2